# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efe4da4c9ce7c11d8b9c5069dfa6260acfe3584ae04d945a87ea35bb6afd1e75d6a7c860fab8a4ac481058e7768f45f3980b04050ca0f65e148cd0355ae559e0

test:
  secret_key_base: 51a919a7e5fe5c4cc99b2c6289f3bf15063a2afd7f85b72016273d59cb97a5935c7bfe2c3ff98328f28b72e3dd251194c58721c284e4d3722825d6cfe7fb4f01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
